name: Teste Automacao Imagem

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

  workflow_dispatch:

jobs:

  teste_jobs:
   name: Executando o job de teste
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: step 1
      run: echo Olá, rodou

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: 'thiagomdr3'
        password: ${{secrets.DOCKERHUB_PASSWORD}}

          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.12.0
      with:
        context: ./Automacao.Imagem.Docker/
        tags: 'latest'
        push: true
